create table if not exists public.refeicoes (
  id bigint generated by default as identity primary key,
  nome text not null,
  descricao text not null,
  calorias integer not null default 0,
  proteinas double precision not null default 0,
  carboidratos double precision not null default 0,
  gorduras double precision not null default 0,
  data_refeicao text not null,
  local text not null default '',
  avaliacao integer not null default 3 check (avaliacao between 1 and 5)
);

alter table public.refeicoes
  add column if not exists proteinas double precision not null default 0,
  add column if not exists carboidratos double precision not null default 0,
  add column if not exists gorduras double precision not null default 0,
  add column if not exists local text not null default '',
  add column if not exists avaliacao integer not null default 3;
